config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#start'

  resources :groups, only: [:index, :show] do
    resources :users, only: [:index]
  end
  resources :teachers, only: [:index, :show]
  resources :auditoriums, only: [:index, :show]

  get 'start', to: 'pages#start'
  get 'vk_init', to: 'pages#vk_init'
  get '/auth/:provider/callback', to: 'pages#callback'
  get 'logout', to: 'pages#logout'

  get 'offline', to: 'pages#offline'
  get 'sw', to: 'js#sw'

  get 'user/edit'
  put 'user/update'
end

app/views/_shared/_build.html.erb
dev

app/views/_shared/_google_analytics.html.slim
//- if Rails.env.production?
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-45614097-1', 'cravs.com');
  ga('require', 'displayfeatures');

app/views/_shared/_schedule.html.slim
- if @schedule.present?
  - @schedule.group_by(&:group_by_date).each do |key, value|
    .panel class=(key.to_date == Date.today && !@offline ? 'panel-primary' : 'panel-info')
      .panel-heading
        = l(key.to_date, :format => '%A, %e %b %Y')
        |  (#{ t('.pair', :count => value.count) })
      table class="table"
        tbody
        - value.each do |entity|
          tr class=(entity.entity_type.important ? 'warning' : '')
            td style="width:10%;"
              | #{ entity.start.strftime('%k:%M') } - #{ entity.end.strftime('%k:%M') }
            td style="width:35%;"
              = entity.subject.name
              - if entity.entity_type.present?
                - if entity.entity_type.name.present?
                  |  (<abbr title="#{ entity.entity_type.name }">#{ entity.entity_type.shot_name }</abbr>)
            - if @schedule_view == 'aud'
              td style="width:10%;"
                - if entity.auditorium
                  = link_to entity.group.name, group_path(entity.group)
            - else
              td style="width:10%;"
                - if entity.auditorium
                  = link_to entity.auditorium.name, auditorium_path(entity.auditorium)
            - if @schedule_view == 'group'
              td style="width:35%;"
                = link_to entity.group.name, group_path(entity.group)
            - else
              td style="width:35%;"
                = link_to entity.teacher.full_name, teacher_path(entity.teacher)
- else
  .alert.alert-info Расписание отсутствует!